export { HomePage } from "./Home/HomePage"
export { ProductPage } from "./Product/ProductPage"
export { ProductDetail } from "./Micelaneous/ProductDetail"
export { SuccessfulPurchase } from "./Micelaneous/SuccessfulPurchase"
export { CartPage } from "./Cart/CartPage"